
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Not = 2;
  public static final int EOF = 0;
  public static final int Apertura = 5;
  public static final int And = 3;
  public static final int Or = 4;
  public static final int Cierre = 6;
  public static final int False = 9;
  public static final int PuntoComa = 7;
  public static final int error = 1;
  public static final int True = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Not",
  "And",
  "Or",
  "Apertura",
  "Cierre",
  "PuntoComa",
  "True",
  "False"
  };
}

